module.exports = {
        axios: require('axios'),
        chalk: require('chalk'),
        commander: require('commander'),
        express: require('express'),
        lodash: require('lodash'),
        moment: require('moment'),
        react: require('react'),
        reactDom: require('react-dom'),
        request: require('request'),
        tslib: require('tslib'),
        vueJsModal: require('vue-js-modal'),
        bootstrap: require('bootstrap'),
        liveServer: require('live-server'),
        cropperjs: require('cropperjs'),
        yo: require('yo'),
};
